apiVersion: v1
kind: Service
metadata:
  name: car-game
  namespace: namespace-workflow-1735566293826
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: car-game
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000